#!/bin/bash
#=================================================================================
# Configure an instance of Ubuntu 16.04 Desktop as a Scala training environment.
#
# Version: 2.0.0
# Date: 11 Jun 2016
# Author: Dave Nicolette
#=================================================================================

clear
echo ' '
echo 'Provisioning this instance as a Scala training environment'
echo 'setup script: version 2.0.0 11 Jun 2016'
echo 'Assumes Ubuntu 16.04 Desktop 64-bit'
echo ' '
echo 'Applying system software updates...'

#sudo apt update
#sudo apt -y dist-upgrade

echo ' '
mkdir -p "$HOME/bin"
echo "Prepending $HOME/bin to PATH at the end of $HOME/.profile"
echo "PATH=$HOME/bin:$PATH" >> .profile

# This could be true if the setup script was obtained from a source other than github

if [ ! -f /usr/bin/git ]; then
    echo ' '
    echo 'git is required and is not installed'
    echo 'intalling git...'
    sudo apt install -y git
fi

export INSTALL_DIR="$HOME/provision-ubuntu-16.04-scalatrain"
export COMMON_DIR="provision-ubuntu-16.04-common"

# On a re-run of the setup script, this repo will already have been cloned

if [ ! -d "./$COMMON_DIR" ]; then
    git clone "git://github.com/neopragma/$COMMON_DIR"
fi

"./$COMMON_DIR/install_development_basics"

echo ' '
echo 'Installing OpenJDK 8'

sudo apt -y install openjdk-8-jdk-headless

echo ' '
echo 'Installing Scala'

pushd "$HOME/tmp"
sudo apt remove scala-library scala
sudo wget www.scala-lang.org/files/archive/scala-2.12.0-M4.deb
sudo dpkg -i scala-2.12.0-M4.deb
sudo apt update
sudo apt -y install scala

echo ' '
echo 'Installing SBT'

wget -O sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.9/sbt-launch.jar
cp sbt-launch.jar "$HOME/bin"
popd
cp sbt "$HOME/bin"
chmod +x "$HOME/bin/sbt"

echo ' '
echo 'Setting a Scala-themed desktop background image'
gsettings set org.gnome.desktop.background picture-uri "file:///$INSTALL_DIR/background.jpg"

echo ' '
echo 'Setting Unity launcher favorites'
gsettings set com.canonical.Unity.Launcher favorites "['nautilus.desktop', 'firefox.desktop', 'eclipse.desktop', 'atom.desktop', 'gnome-terminal.desktop']"

echo ' '
if [ -d "$HOME/workspace/starter" ]; then
    echo "A directory named 'starter' already exists at $HOME/workspace."
    echo "NOT COPYING the starter project to that location."
    echo "If you need it later, you can copy it from $INSTALL_DIR/starter."
else
    echo "Copying the 'starter' project files to $HOME/workspace/starter"
    pushd "$HOME/workspace"
    cp -r "$INSTALL_DIR/starter" .
    popd
fi

echo ' '
if [ -f "$HOME/.sbt/0.13/plugins/build.sbt" ]; then
    echo "A build.sbt file exists at $HOME/.sbt/0.13/plugins; not copying over it"
else
    echo "Copying build.sbt to $HOME/.sbt/0.13/plugins"
    pushd "$HOME"
    mkdir -p .sbt/0.13/plugins
    cd .sbt/0.13/plugins
    cp "$INSTALL_DIR/sbt-plugins/build.sbt" .
    popd
fi

if [ ! -f "$HOME/bin/verify" ]; then
    echo ' '
    echo "Copying the verify script to $HOME/bin"
    cp verify "$HOME/bin"
fi

echo ' '
echo 'Verifying the configuration'
echo '(You can do this any time by running the script, ~/bin/verify)'
./verify

echo ' '
echo 'Copying the help file (html) to the desktop'
cp help.html "$HOME/Desktop"

firefox "$HOME/Desktop/help.html"
