#!/bin/bash
#===============================================================================
# See if this instance appears to have everything installed as expected.
# This is for provision-ubuntu-16.04-javatrain.
#
# Version: 1.0.0
# Date: 05 Jun 2016
# Author: Dave Nicolette
#===============================================================================

echo
echo '============================================================='
echo 'Verifying configuration of Scala training environment'
echo 'This is version 1.0.0 of the verify script (10 Jun 2016)'

declare -i errors=0

declare -a pkg
pkg[${#pkg[@]}]='build-essential'
pkg[${#pkg[@]}]="linux-headers-$(uname -r)"
pkg[${#pkg[@]}]='dkms'
pkg[${#pkg[@]}]='python-software-properties'

for name in "${pkg[@]}"
do
  if [[ -n "$(dpkg -l | grep ${name})" ]]; then
    dpkg -l | grep "${name}" | awk -F" " '{print "       package " $2 "\tversion " $3}'
  else
      echo "ERROR: package ${name} was expected but is not installed"
      errors="${errors}+1"
  fi
done

declare -a app
app[${#app[@]}]="/usr/bin/atom"
app[${#app[@]}]="/opt/eclipse/eclipse"
app[${#app[@]}]="/usr/bin/git"
app[${#app[@]}]="/usr/lib/jvm/java-8-openjdk-amd64/bin/java"
app[${#app[@]}]="/usr/bin/mvn"

declare -a ver
ver[${#ver[@]}]=$(atom --version | grep "Atom" | awk -F" " '{print $3}')
ver[${#ver[@]}]=$(git --version | awk -F" " '{print $3}')
ver[${#ver[@]}]=$(git --version | awk -F" " '{print $3}')
ver[${#ver[@]}]=$(java -version 2> tmp; cat tmp | head -1 | awk -F" " '{print $3}')
ver[${#ver[@]}]=$(mvn --version | head -1 | awk -F" " '{print $3}')

#for name in "${app[@]}"
element_count=${#app[@]}
index=0
while [ "$index" -lt "$element_count" ]
do
  if [[ -e "${app[$index]}" ]]; then
      echo "       program ${app[$index]} | version ${ver[$index]}"
  else
      echo "ERROR: program ${app[$index]} was expected but is not installed"
      errors="${errors}+1"
  fi
  ((index++))
done

if [[ -e /opt/eclipse/plugins/org.scala-ide.scala210.jars_4.4.1.201605041056.jar ]]; then
    echo "       Scala IDE plugin for Eclipse appears to be installed"
else
    echo "ERROR: Scala IDE plugin for Eclipse was expected but is not installed"
    errors="${errors}+1"
fi

test "${errors}" -eq 0 && echo "...configuration is as expected." || echo "...${errors} expected package(s) or application(s) not found! Configuration may not function as desired."
